---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/xyhhx/home-ops
  ref:
    branch: master
  secretRef:
    name: home-ops-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: global-vars
        optional: false
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: workload-secrets
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/xyhhx/home-ops-secrets
  ref:
    branch: cert-manager-2
  secretRef:
    name: home-ops-secrets-deploy-key
  ignore: |
    # exclude all
    /*
    # include namespaces directory
    !/namespaces
