---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-nfs-truenas
spec:
  storageClassName: nextcloud-data-nfs-truenas
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.69.69.5
    path: /mnt/shinji/home
  mountOptions:
    - nolock
    - async
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-nfs-truenas
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-data-nfs-truenas
  resources:
    requests:
      storage: 1Ti
