---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-nfs
spec:
  storageClassName: nextcloud-data-nfs
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.69.69.4
    path: /export/nextcloud
  mountOptions:
    - nolock
    - async
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-nfs
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-data-nfs
  resources:
    requests:
      storage: 1Ti
