---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noodle
  template:
    metadata:
      labels:
        app: noodle
    spec:
      containers:
      - name: noodle
        image: xyhhx/noodleapp
        env:
          - name:  FOOD_DATA_CENTRAL_API_KEY
            valueFrom:
              secretKeyRef:
                name:  fdc-api-token
                key:  token
        ports:
        - name:  web
          containerPort:  3000
        resources:
---
kind: Service
apiVersion: v1
metadata:
  name:  noodle
spec:
  selector:
    app:  noodle
  type:  NodePort
  ports:
  - name:  web
    port:  80
    targetPort:  3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-traefik-forward-auth@kubernetescrd
spec:
  tls:
    - hosts:
        - noodle.ab.hor.rent
      secretName: tls-noodle-ingress-http
  rules:
    - host: noodle.ab.hor.rent
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noodle
                port:
                  number: 80
