---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev-environment
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: "1.20.4"
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    persistence:
      enabled: false
    gitea:
      config:
        APP_NAME: "Abhorrent Gitea"
        service:
          DISABLE_REGISTRATION: true
        server:
          ROOT_URL: "https://gitea.ab.hor.rent"
          DOMAIN: "gitea.ab.hor.rent"
          SSH_DOMAIN: "gitea.ab.hor.rent"
        database:
          DB_TYPE: postgres
          HOST: postgresql-gitea.dev-environment.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
      admin:
        existingSecret: gitea-admin-secret
      oauth:
        - name: "Keycloak"
          provider: "openidConnect"
          existingSecret: gitea-oauth-secret
          autoDiscoverUrl: "https://auth.ab.hor.rent/realms/homelab/.well-known/openid-configuration/"
          skipLocal2fa: true

      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
