---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev-environment
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 1m
  values:
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false

    persistence:
      enabled: false

    gitea:
      config:
        database:
          DB_TYPE: postgres
          HOST: postgresql-gitea.dev-environment.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
          PASSWD: gitea
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
