---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collabora-code
  namespace: collabora
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - collabora.ab.hor.rent
      secretName: tls-collabora-code-ingress-http
  rules:
    - host: collabora.ab.hor.rent
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collabora-code
                port:
                  name: http
