---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-secrets
  namespace: flux-system
spec:
  path: ./namespaces/dev-environment
  prune: true
  sourceRef:
    kind: GitRepository
    name: workload-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-release
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/dev-environment/gitea/release
  prune: true
  dependsOn:
    - name: openebs-jiva-config
    # - name: gitea-postgresql-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-config
  namespace: flux-system
spec:
  dependsOn:
    - name: gitea-release
  path: ./kubernetes/workloads/dev-environment/gitea/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30s
  retryInterval: 2m
  timeout: 15m
