---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 5m
  chart:
    spec:
      chart: forgejo
      version: "0.14.0"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: "1.21.1-0"
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    persistence:
      enabled: false
    gitea:
      config:
        APP_NAME: "Abhorrent forgejo"
        actions:
          ENABLED: true
          DEFAULT_ACTIONS_URL: https://code.forgejo.org
        service:
          DISABLE_REGISTRATION: true
        server:
          ROOT_URL: "https://forgejo.ab.hor.rent"
          DOMAIN: "forgejo.ab.hor.rent"
          SSH_DOMAIN: "forgejo.ab.hor.rent"
        database:
          DB_TYPE: postgres
          HOST: postgresql-forgejo.forgejo.svc.cluster.local:5432
          NAME: forgejo
          USER: forgejo
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
      admin:
        existingSecret: forgejo-admin-secret
      oauth:
        - name: "Keycloak"
          provider: "openidConnect"
          existingSecret: forgejo-oauth-secret
          autoDiscoverUrl: "https://auth.ab.hor.rent/realms/homelab/.well-known/openid-configuration/"
          skipLocal2fa: true

      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
