---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 5m
  chart:
    spec:
      chart: forgejo
      version: "0.14.0"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: forgejo-signing-key-fpr
      valuesKey: fingerprint
      targetPath: "gitea.config.repository\\.signing.SIGNING_KEY"
  values:
    image:
      tag: "1.21.1-0"
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    gitea:
      config:
        APP_NAME: "Abhorrent forgejo"
        actions:
          ENABLED: true
          DEFAULT_ACTIONS_URL: https://code.forgejo.org
        service:
          DISABLE_REGISTRATION: true
        server:
          ROOT_URL: "https://forgejo.ab.hor.rent"
          DOMAIN: "forgejo.ab.hor.rent"
          SSH_DOMAIN: "forgejo.ab.hor.rent"
        ui:
          THEMES: "forgejo-auto,forgejo-light,forgejo-dark,auto,gitea,arc-green,pitch-black"
          DEFAULT_THEME: "pitch-black"
        database:
          DB_TYPE: postgres
          HOST: postgresql-forgejo.forgejo.svc.cluster.local:5432
          NAME: forgejo
          USER: forgejo
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
        repository:
          DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.wiki,repo.projects,repo.packages,repo.actions
        repository.signing:
          INITIAL_COMMIT: always
          CRUD_ACTIONS: pubkey, twofa, parentsigned
          WIKI: never
          MERGES: pubkey, twofa, basesigned, commitssigned
      admin:
        existingSecret: forgejo-admin-secret
      oauth:
        - name: "Keycloak"
          provider: "openidConnect"
          existingSecret: forgejo-oauth-secret
          autoDiscoverUrl: "https://auth.ab.hor.rent/realms/homelab/.well-known/openid-configuration/"
          skipLocal2fa: true
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
    extraVolumes:
      - name: forgejo-themes
        configMap:
          name: forgejo-themes
    extraContainerVolumeMounts:
      - name: forgejo-themes
        readOnly: true
        mountPath: "/data/gitea/public/assets/css"
    signing:
      enabled: true
      gpgHome: /data/git/.gnupg
      existingSecret: forgejo-signing-key
    service:
      http:
        type: LoadBalancer
        loadBalancerIP: 10.69.0.13
        clusterIP:
        annotations:
          metallb.universe.tf/allow-shared-ips: forgejo
      ssh:
        type: LoadBalancer
        loadBalancerIP: 10.69.0.13
        clusterIP:
        annotations:
          metallb.universe.tf/allow-shared-ips: forgejo
        ports:
          ssh:
            enabled: true
            port: 30022
            protocol: TCP
            targetPort: 30022
