---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: .
      version: "0.3.0"
      sourceRef:
        kind: GitRepository
        name: brianmcarey-jellyfin
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - jellyfin.ab.hor.rent
      tls:
        - hosts:
            - jellyfin.ab.hor.rent
          secretName: tls-jellyfin-ingress-http
    persistence:
      config:
        enabled: true
        size: 8Gi
      media:
        enabled: true
        existingClaim: media-nfs
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
      requests:
        cpu: "250m"
        memory: "512Mi"
