apiVersion: v1
kind: ResourceQuota
metadata:
  name: keycloak
  namespace: keycloak
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: "512Mi"
    limits.cpu: "250m"
    limits.memory: "1Gi"
