---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sliding-sync-proxy
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/matrix/sliding-sync-proxy/release
  prune: true
  dependsOn:
    - name: openebs-jiva-config
    - name: sliding-sync-proxy-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
