apiVersion: v1
kind: ResourceQuota
metadata:
  name: metallb
  namespace: metallb-system
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.  memory: "2Gi"
