apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-jiva
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: jiva
      version: "3.2.0"
      sourceRef:
        kind: HelmRepository
        name: openebs-jiva
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
