apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-environment
  namespace: dev-environment
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
