---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: "3.5.13"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 1m
  values:
    nextcloud:
      host: nextcloud.ab.hor.rent
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
    persistence:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      host: postgresql-nextcloud.nextcloud.svc.cluster.local:5432
      type: postgresql
      database: nextcloud
      user: nextcloud
      existingSecret:
        secretName: nextcloud-secrets
        passwordKey: db-password
