---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: "3.5.13"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 1m
  values:
    nextcloud:
      host: cloud.ab.hor.rent
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      extraEnv:
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: oidc-client-secret
      extraVolumes:
        - name: media-nfs-vol
          persistentVolumeClaim:
            claimName: nextcloud-media-nfs-truenas
      extraVolumeMounts:
        - name: media-nfs-vol
          mountPath: "/mnt/media-nfs"
      configs:
        oidcs-login.config.php: |-
          <?php
            $CONFIG = [
              'oidc_login_client_id'            => 'cloud.ab.hor.rent',
              'oidc_login_client_secret'        => getenv("OIDC_CLIENT_SECRET"),
              'oidc_login_provider_url'         => 'https://auth.ab.hor.rent/realms/homelab',
              'oidc_login_logout_url'           => 'https://cloud.ab.hor.rent/apps/oidc_login/oidc',
              'oidc_login_auto_redirect'        => true,
              'oidc_login_redir_fallback'       => true,
              'oidc_login_end_session_redirect' => true,
              'oidc_login_disable_registration' => false,
              'oidc_login_attributes' => [
                'id'   => 'preferred_username',
                'mail' => 'email',
                'is_admin' => 'nextcloud_admin'
              ],
              'overwriteprotocol' => 'https',
              'oidc_login_code_challenge_method' => 'S256',
            ]
          ?>
    persistence:
      enabled: true
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data-nfs-truenas
    startupProbe:
      enabled: true
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 10
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      host: postgresql-nextcloud.nextcloud.svc.cluster.local:5432
      type: postgresql
      database: nextcloud
      user: nextcloud
      existingSecret:
        secretName: nextcloud-secrets
        passwordKey: db-password
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
