# https://fluxcd.io/flux/guides/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: "3.5.13"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 1m
  values:
    nextcloud:
      host: nextcloud.ab.hor.rent
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
    persistence:
      enabled: true
      storageClass: nfs-client
      size: 50Gi
      accessModes: ReadWriteMany
    postgresql:
      enabled: true
      persistence:
        enabled: true
      auth:
        database: nextcloud
        existingSecret: postgres-secrets
        secretKeys:
          adminPasswordKey: admin-password
          userPasswordKey: user-password
          replicationPasswordKey: replication-password
