---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner-release-truenas
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/nfs-provisioner/nfs-subdir-external-provisioner/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: global-vars
        optional: false
