---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-secrets
  namespace: flux-system
spec:
  path: ./namespaces/forgejo
  prune: true
  sourceRef:
    kind: GitRepository
    name: workload-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-release
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/forgejo/forgejo/release
  prune: true
  dependsOn:
    - name: openebs-jiva-config
    - name: forgejo-secrets
    - name: forgejo-postgresql-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: forgejo-release
  path: ./kubernetes/workloads/forgejo/forgejo/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30s
  retryInterval: 2m
  timeout: 15m
