---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: global-vars
data:
  TRUENAS_NFS_ADDRESS: 10.69.69.5
  TRUENAS_NFS_EXPORT_PATH: /mnt/shinji/k8s-data-public
  BASE_DOMAIN_NAME: "ab.hor.rent"
