---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: global-vars
data:
  NFS_ADDRESS: 10.69.69.4
  NFS_EXPORT_PATH: /export/k8s-data-public
  METALLB_POOL: "10.69.69.10-10.69.69.99"
  CERT_MANAGER_DNS_COMMON_NAME: "ab.hor.rent"
  CERT_MANAGER_DNS_WILDCARD: "*.ab.hor.rent"
