---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nice-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.69.69.10-10.69.69.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: metallb-system
