---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner-release
  namespace: flux-system
spec:
  path: ./kubernetes/flux/workloads/nfs-subdir-external-provisioner/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
