---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-jiva
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: jiva
      version: "3.3.0"
      sourceRef:
        kind: HelmRepository
        name: openebs-jiva
        namespace: flux-system
      interval: 1m
  values:
    storageClass:
      isDefaultClass: true
    jivaOperator:
      resources:
        limits:
          cpu: "250m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"
    csiController:
      resources:
        limits:
          cpu: "250m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"
    csiNode:
      resources:
        limits:
          cpu: "250m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              name: openebs-jiva-csi-node
            spec:
              template:
                spec:
                  hostPID: true
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
