---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: kube-system
data:
  config.json: |-
    {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "username": "renovatebot",
      "gitAuthor": "Renovate Bot <renovatebot@forgejo.ab.hor.rent>",
      "autodiscover": true,
      "optimizeForDisabled": true,
      "kubernetes": {
        "fileMatch": [
          "^kubernetes/workloads/.*resources.yaml",
          "^kubernetes/workloads/.*ks.yaml",
          "^kubernetes/workloads/.*helm-release.yaml"
        ]
      },
      "packageRules": [
        {
          "matchUpdateTypes": ["minor", "patch"],
          "matchCurrentVersion": "!/^0/",
          "automerge": true
        }
      ]
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: kube-system
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:37.99.1
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_PLATFORM_COMMIT
                  value: "true"
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
