---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: kube-system
data:
  config.json: |-
    {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "username": "renovatebot",
      "gitAuthor": "Renovate Bot <renovatebot@forgejo.ab.hor.rent>",
      "autodiscover": true,
      "optimizeForDisabled": true,
      "kubernetes": {
        "fileMatch": [
          "^kubernetes/.*resources.yaml",
          "^kubernetes/.*config.yaml",
          "^kubernetes/.*kustomization.yaml",
          "^kubernetes/.*helm-release.yaml"
        ]
      },
      "packageRules": [
        {
          "matchUpdateTypes": ["minor", "patch"],
          "matchCurrentVersion": "!/^0/",
          "automerge": true
        }
      ],
      "customManagers": [
        {
          "customType": "regex",
          "description": "Apply an explicit forgejo digest field match",
          "fileMatch": ["helm-release\\.ya?ml"],
          "matchStrings": [
            "(?<depName>forgejo\\/forgejo)\\n(?<indentation>\\s+)tag: (?<currentValue>[^@].*?)\\n\\s+digest: (?<currentDigest>sha256:[a-f0-9]+)"
          ],
          "datasourceTemplate": "docker",
          "packageNameTemplate": "codeberg.org/{{depName}}",
          "autoReplaceStringTemplate": "{{depName}}\n{{indentation}}tag: {{newValue}}\n{{indentation}}digest: {{#if newDigest}}{{{newDigest}}}{{else}}{{{currentDigest}}}{{/if}}"
        }
      ],
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: kube-system
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:37.99.1
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_PLATFORM_COMMIT
                  value: "true"
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
