---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: kube-system
data:
  config.json: |-
    {
      "username": "frenovate[bot]",
      "gitAuthor": "frenovate[bot] <146583444+frenovate[bot]@users.noreply.github.com>",
      "dryRun" : "true"
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: kube-system
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:35.14.4
              args:
                - xyhhx/home-ops
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                limits:
                  memory: "2G"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
