---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: kube-system
data:
  config.json: |-
    {
      "username": "frenovate[bot]",
      "gitAuthor": "frenovate[bot] <146583444+frenovate[bot]@users.noreply.github.com>"
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: kube-system
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: secrets-init
              image: ghcr.io/xyhhx/init-gh-token:main
              env:
                - name:  APP_ID
                  valueFrom:
                    secretKeyRef:
                      name:  renovate-env
                      key: RENOVATE_GH_APP_ID
                - name:  PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name:  renovate-env
                      key: RENOVATE_GH_APP_PRIVATE_KEY
              volumeMounts:
                - mountPath: /mnt
                  name: token-vol
          containers:
            - name: renovate
              image: renovate/renovate:37.8.1
              command:
                - /bin/sh
              args:
                - -c
                - export RENOVATE_TOKEN=$(cat /mnt/token); renovate xyhhx/home-ops
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_PLATFORM_COMMIT
                  value: "true"
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                limits:
                  memory: "2G"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
                - name: token-vol
                  mountPath: /mnt
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
            - name: token-vol
              emptyDir: {}
