---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: collabora-code
  namespace: collabora
spec:
  interval: 5m
  chart:
    spec:
      chart: collabora-code
      version: "2.5.1"
      sourceRef:
        kind: HelmRepository
        name: chrisingenhaag
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: "23.05.0.5.1"
    collabora:
      domain: cloud\\.ab\\.hor\\.rent
      server_name: collabora\.ab\.hor\.rent
      existingSecret:
        enabled: true
        secretName: collabora-credentials
        usernameKey: username
        passwordKey: password
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
