---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openebs
  - monitoring
  - metallb
  - nfs-provisioner
  - cert-manager
  - flux-system
  - kube-system
  - keycloak
  # - dev-environment
  - nextcloud
  - collabora
  - media
  - matrix
  - default
