---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openebs
  - monitoring
  - metallb
  - nfs-provisioner
  - cert-manager
  - flux-system
  - kube-system
  - authentik
  # - ldap
  # - keycloak
  # - forgejo
  # - nextcloud
  # - collabora
  - media
  # - matrix
  - default
