---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nice-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.69.0.0/18 # 10.69.0.1-10.69.63.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - nice-pool
    - nice-pool-2
