---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: collabora-secrets
  namespace: flux-system
spec:
  path: ./namespaces/collabora
  prune: true
  sourceRef:
    kind: GitRepository
    name: workload-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: collabora-release
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/collabora/collabora/release
  prune: true
  dependsOn:
    - name: collabora-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: collabora-config
  namespace: flux-system
spec:
  dependsOn:
    - name: collabora-release
  path: ./kubernetes/workloads/collabora/collabora/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30s
  retryInterval: 2m
  timeout: 15m
