apiVersion: v1
kind: ResourceQuota
metadata:
  name: flux-system
  namespace: flux-system
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.  memory: "1Gi"
