apiVersion: v1
kind: ResourceQuota
metadata:
  name: flux-system
  namespace: flux-system
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.  memory: "2Gi"
