---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql-forgejo
  namespace: forgejo
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.8.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    global:
      postgresql:
        auth:
          database: forgejo
          username: forgejo
          existingSecret: postgres-secrets
