---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  storageClassName: media-nfs
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_ADDRESS}"
    path: /export/media
  mountOptions:
    - nolock
    - async
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  resources:
    requests:
      storage: 1Ti
