apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring
  namespace: monitoring
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: "1Gi"
    limits.cpu: "1.5"
    limits.memory: "2Gi"
