---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops-secrets
  namespace: flux-system
spec:
  path: ./namespaces/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: workload-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops-release
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/flux-system/weave-gitops/release
  prune: true
  dependsOn:
    - name: weave-gitops-secrets
    - name: openebs-jiva-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
