---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: "16.1.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-creds
      passwordSecretKey: password
    ingress:
      enabled: true
      hostname: auth.ab.hor.rent
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    extraEnvVars:
      - name: KC_HOSTNAME_URL
        value: https://auth.ab.hor.rent
      - name: KC_HOSTNAME_ADMIN_URL
        value: https://auth.ab.hor.rent
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
