---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: "16.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-creds
      passwordSecretKey: password
    ingress:
      enabled: true
      hostname: auth.ab.hor.rent
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
